export var data_array = [
    ["Jak nazywał się ostatni król z dynastii Jagiellonów?","Zygmunt III Waza","Zygmunt Stary","Zygmunt II August", 3],
    ["Gdzie urodził się Mikołaj Kopernik?","Toruń","Kraków","Warszawa", 1],
    ["Kiedy odbyła się Bitwa pod Grunwaldem?","15 lipca 1364","15 lipca 1409","15 lipca 1410", 3],
    ["Jak nazywa się lotnisko, które znajduje się w Warszawie?","Im. Jana Pawla II","Im. Frederica Chopina","Im. Lecha Wałensy", 2],
    ["Kiedy Polska przystąpiła do Unii Europejskiej?","2004","1999","2005", 1],
    ["Jakie historyczne wydarzenie Polacy nazywają «nożem w plecy»?","Atak niemiecki na Polskę 1 września 1939","Atak sowiecki na Polskę 17 września 1939","Bitwa pod Warszawą w 1920", 2],     
    ["Kto przynosi prezenty dzieciom na Boże Narodzenie?","Dziadek Mróz","Święty Mikołaj","Święta Pani Maria", 2],
    ["Gdzie można uszłyszeć hejnał?","W Krakowie","W Warszawie","W Toruniu", 1],
    ["Kto napisał słowa hymnu polskiego?","Karol Józef Wojtyła","Józef Piłsudski","Józef Wybicki", 3],
    ["Polska epopeja narodowa?","Pan Tadeusz","Ogniem i mieczem","Chłopi", 1],
    ["Kiedy w Polsce obchodzą Andrzejki?","29 listopada","6 grudnia","23 listopada", 1],
    ["Gdzie mieszka smok Wawelski?","W grocie","Na drzewie","W morzu", 1],
    ["Najdłuższa rzeka Polski?","Warta","Wisła","Odra", 2],
    ["Kto jest patronem Polski?","Jerzy Popiełuszko","Jan Paweł II","Św. Wojciech", 3],
    ["Jak się nazywa wielki polski malarz, który żył w latach 1838-1893 w Krakowie?","Henryk Sienkiewicz","Jan Matejko", "Jacek Malczewski", 2],
    ["Kiedy w Polsce obchodzi się Dzień Niepodległości?","15 sierpnia","3 maja", "11 listopada", 3],
    ["Jak się nazywa drugi dzień Swiąt Wielkanocnych (po Niedziele Wielkanocnej)?","Drugi Poniedziałek","Śmigus Dyngus", "Wigilia", 2],
    ["Jaka część Polski zwana jest \"krainą tysiąca jezior\"","Mazury","Beskidy", "Trójmiasto", 1],
    ["Ile wojewódstw jest w Polsce teraz?","16","15", "18", 1], 
    ["Kto obecnie jest Prezydentem Polski?","Beata Maria Szydło","Andrzej Sebastian Duda", "Mateusz Jakub Morawiecki", 2],
    ["Kiedy wybuchło powstanie styczniowe?","1863","1831", "1861", 1],
    ["Z jakimi państwami graniczy Polska?","Litwa, Białoruś, Ukraina, Niemcy, Rosja, Austria, Czechy","Litwa, Białoruś, Ukraina, Niemcy, Słowacja, Czechy", "Litwa, Białoruś, Ukraina, Niemcy, Rosja, Słowacja, Czechy", 3],
    ["Jak się nazywa Hymn Polski?","Mazurek Dąbrowskiego","Hymn Polski", "Rota", 1],
    ["Kim był Jerzy Popiełuszko?","Poetem","Malarzem", "Księdzem", 3],
    ["Kto był pierwszym królem Polski?","Bolesław I Chrobry","Mieszko I", "Stanisław August Poniatowski", 1],
    ["Kiedy był III rozbiór RP?","1791","1795", "1793", 2],
    ["Kiedy obchodzi się Prima Aprilis?","1 czerwca","1 stycznia", "1 kwietnia", 3],
    ["Przy kim Polska wstąpiła do Schengen?","Lech Kaczyński","Aleksander Kwaśniewski", "Bronisław Komorowski", 2],
    ["Jakie godło ma Warszawa?","Wieża","Syrenka", "Orzeł", 2],
    ["Z czym się kojarzy w Polsze 1980 rok?","Cud nad Wislą","Stan wojenny", "Solidarność", 3],
    ["Jaka legenda opowiada o powstaniu Państwa Polskiego?","O Lechu, Czechu i Rusie","O lajkoniku", "O Smoku Wawelskim", 1],
    ["Kiedy obchodzi się Dzień Solidarności?","11 listopada","1 września", "31 sierpnia", 3],
    ["Kim był Jan Henryk Dąbrowski?","Autorem tekstu \"Mazurek Dąbrowskiego\"","Generałem", "Księdzem", 2],
    ["Jak się nazywa miecz koronacyjny Królów Polski?","Szczerbiec","Miecz Królewski", "Ekskalibur", 1],
    ["Jak się nazywa święto rolników?","Tłusty czwartek","Dożynki", "Sylwestr", 2],
    ["Co nie było oznaką władcy, używaną podczas ceremonii koronacyjnych?","jabłko","berło", "orzeł", 3],
    ["Z czego słynie Malbork?","Krzyżacki zamek","Uniwersytet Jagielloński", "Wawel", 1],
    ["Najdłuższa rzeka Polski?","Bug","Wisła", "Warta", 2],
    ["Jak się nazywa święto, kiedy ksiądz mówi (posypując głowy popiołem): \"Prochem jesteś i w proch się obrócisz\"?","Zaduszki","Boże Ciało", "Środa Popielcowa", 3],
    ["Kiedy był I rozbiór RP?","1772","1773", "1791", 1],
    ["Kto z polskich noblistów dwukrotnie dostał Nagrodę Nobla?","Lech Wałęsa","Maria Skłodowska-Curie", "Henryk Sienkiewicz ", 2],
    ["Kim był Adam Mickiewicz?","Pisarz","Kompozytorz", "Poeta", 3],
    ["Dzięki komu Warszawa została stolicą Polski?","Zygmunt III Waza","Kazimierz III Wielki", "Stanisław August Poniatowski", 1],
    ["Kto jest autorem utworów \"Ogniem i mieczem\", \"Potop\", \"Quo vadis?\"","Władysław Reymont","Henryk Sienkiewicz", "Czesław Miłosz", 2],
    ["Kto \"zastał Polskę drewnianą, a zostawił murowaną\"?","Zygmunt III Waza","Bolesław I Chrobry", "Kazimierz III Wielki", 3],
    ["Król, który zwyciężył w bitwie pod Wiednem w 1683 roku i był autorem \"Listów do Marysieńki\"?","Jan III Sobieski","Władysław Jagiełło", "Kazimierz III Wielki", 1],
    ["Kto jest autorem (malarzem) obrazów historycznych, takich jak: \"Bitwa pod Grunwaldem\", \"Konstytucja 3 maja\"","Wojciech Kossak","Jan Matejko", "Jacek Malczewski", 2],
    ["Kto z polskich noblistów dostał nagrodę Nobla w 1996?","Maria Curie-Skłodowska","Lech Wałęsa", "Wisława Szymborska", 3],
    ["Dzięki komu Polska przyjęła chrzest?","Mieszko I","Bolesław I Chrobry", "Władysław Jagiełło", 1],
    ["W czasie kadencji którego prezydenta Polska wstąpiła do NATO","Lech Kaczyński","Aleksander Kwaśniewski", "Bronisław Komorowski", 2],
    ["Wymień polskich prezydentów RP III (w porządku chronologicznym)","Lech Wałęsa, Lech Kaczyński, Bronisław Komorowski, Aleksander Kwaśniewski, Andrzej Duda","Wojciech Jaruzelski, Lech Wałęsa, Lech Kaczyński, Bronisław Komorowski, Aleksander Kwaśniewski, Andrzej Duda", "Wojciech Jaruzelski, Lech Wałęsa, Aleksander Kwaśniewski, Lech Kaczyński, Bronisław Komorowski, Andrzej Duda", 3],
    ["Kto napisał muzykę do hymnu polskiego?","Józef Wybicki","Nieznany", "Jan Dąbrowski", 2],
    ["Kim był Tadeusz Kościuszko?","Marszałkiem","Księdzem", "Przywódcą powstania narodowego", 3],
    ["Kto jest autorem słów hymnu polskiego?","Józef Wybicki","Nieznany", "Jan Dąbrowski", 1],
    ["Kto jest autorem \"Nad Niemnem\"?","Adam Mickiewicz","Eliza Orzeszkowa", "Czesław Miłosz", 2],
    ["Kto z polskich reżyserów dostał Oscara?","Aleksander Kwaśniewski","Krzysztof Penderecki", "Andrzej Wajda", 3],
    ["Kim była Świeta Jadwiga?","Królem/Królową","Żoną Mieszko I", "Poetką", 1],
    ["Kto był pierwszym prezydentem Polski?","Wojciech Jaruzelski","Gabriel Narutowicz", "Lech Wałęsa", 2],
    ["Kto przeniósł stolicę do Krakowa?","Mieszko I","Bolesław III Krzywousty", "Kazimierz Odnowiciel", 3],
    ["Dzięki komu został założony Uniwiersytet Jagielloński (Akademia Krakowska)?","Kazimierz III Wielki","Władysław Jagiełło", "Zygmunt III Waza", 1],
    ["Kiedy był zjazd w Gnieźnie?","966","1000", "1025", 2],
    ["Data chrztu Polski","998","977", "966", 3],
    ["Kiedy \"Mazurek Dąbrowskiego\" został wybrany himnem oficjalnym Polski?","26 lutego 1927","9 stycznia 1797", "9 stycznia 1779", 1],
    ["Kiedy była koronacja pierwszego króla Polski Bolesława Chrobrego?","1000","1025", "966", 2],
    ["Krewska Unia","1358","1410", "1385", 3],
    ["Kiedy Król Kazimierz I Odnowiciel przeniósł stolicę z Gniezna do Krakowa","1041","1025", "1071", 1],
    ["Kiedy został założony Uniwiersytet Jagielloński (Akademia Krakowska)?","12 grudnia 1569","12 maja 1364", "12 stycznia 1385", 2],
    ["Kiedy była Bitwa pod Grunwaldem?","15 lipca 1411","15 lipca 1444", "15 lipca 1410", 3],
    ["Kiedy Polska wstąpiła do Unii Europiejskiej?","1 maja 2004","12 marca 1999", "12 marca 2004", 1],
    ["Kiedy Polska wstąpiła do NATO?","1 maja 1999","12 marca 1999", "12 marca 2004", 2],
    ["Kiedy był Szwedzki potop?","1660-1665","1655-1665", "1655-1660", 3],
    ["Kiedy Król Żygimont III Waza przeniósł stolicę z Krakowa do Warszawy","1596","1569", "1659", 1],
    ["I wojna światowa","1914-1918","1918-1921", "1917-1921", 1],
    ["Kiedy wybuchło Powstanie Kościuszkowskie?","1863","1794", "1944", 2],
    ["Kiedy wybuchło powstanie Warszawskie?","15 sierpnia 1944","17 wrzesnia 1939", "1 sierpnia 1944", 3],
    ["Unia Lubelska","1 lipca 1569","1 lipca 1567", "1 lipca 1596", 1],
    ["Kiedy został podpisany Pakt Mołotow-Ribbentrop?","23 sierpnia 1939","17 wrzesnia 1939", "9 maja 1945", 1],
    ["Kiedy był \"Cud nad Wisłą\"?","1 sierpnia 1920","15 sierpnia 1920", "15 sierpnia 1944", 2],
    ["Kiedy Karol Józef Wojtyła został wybrany Papieżem Rzymskim?","18 maja 1920","16 października 1980", "16 października 1978", 3],
    ["Kiedy był II rozbiór Rzeczypospolitej Polskiej?","1793","1772", "1790", 1],
    ["Kiedy była podpisana Konstytucja?","1 maja 1771","3 maja 1791", "2 maja 1971", 2],
    ["Kiedy wybuchło Powstanie Listopadowe?","29 listopada 1920","29 listopada 1794", "29 listopada 1830", 3],
    ["Kiedy powstał związek zawodowy Solidarność?","31 sierpnia 1980","16 października 1978", "31 sierpnia 1981", 1],
    ["Kiedy zaczęła się II wojna światowa?","17 września 1939","1 września 1939", "17 września 1939", 2],
    ["Kiedy Polska odzyskała niepodległość?","15 sierpnia 1920","8 maja 1945", "11 listopada 1918", 3],
    ["Kiedy wybuchło Powstanie styczniowe?","22 stycznia 1863","29 stycznia 1865", "22 stycznia 1836", 1],
    ["Jakie wydarzenia wiążą się z datą \"17 września 1939\"?","Początek II wojny światowej","Atak ZSRR na RP", "Zbrodnia Katyńska", 2],
    ["Początek stanu wojennego w Polsce","29 listopada 1983","1 września 1939", "13 grudnia 1981", 3],
    ["Kiedy była Zbrodnia Katyńska?","5 marca 1940","1 września 1939", "17 września 1939", 1],
    ["Jak się nazywa pierwszy dzień Wielkiego Postu?","Adwent","Popielec", "Tłusty Czwartek", 2],
    ["Kiedy obchodzi się Dzień Jana Pawła II?","5 kwietnia","18 maja", "16 października", 3],
    ["Kiedy obchodzi się Dzień Babci?","21 stycznia","6 grudnia", "22 stycznia", 1],
    ["Kiedy obchodzi się Dzień Zaduszny?","1 listopada","2 listopada", "24 listopada", 2],
    ["Kiedy obchodzi się Dzień Ojca?","22 stycznia","26 maja", "23 czerwca", 3],
    ["Kiedy obchodzi się Dzień Wojska Polskiego?","15 sierpnia","31 sierpnia", "1 sierpnia", 1],
    ["Kiedy obchodzi się Dzień Wszystkich Swiętych?","2 listopada","1 listopada", "1 sierpnia", 2],
    ["Kiedy obchodzi się Dzień Dziadka?","6 grudnia","26 maja", "22 stycznia", 3],
    ["Kiedy obchodzi się Dzień Pamięci Ofiar Zbrodni Katyńskiej?","13 kwietnia","1 listopada", "15 sierpnia", 1],
    ["Jaki dzień rozpoczyna ostatni tydzień Karnawału?","Lany poniedziałek","Tłusty czwartek", "Wielki czwartek", 2],
    ["Jak się nazywa uroczysta msza odprawiana w noczy z 24 na 25 grudnia?","Kolęda","Wigilia", "Pasterka", 3],
    ["Co obchodzimy 6 grudnia?","Mikołajki","Andrzejki", "Katarzynki", 1],
    ["Druga nazwa bitwy Cud nad Wisłą?","Bitwa pod Legnicą","Bitwa pod Wiedniem", "Bitwa Warszawska", 3],
    ["Naczelny Wodz Wojska Polskiego w wojnie polsko-sowieckiej?","Wojciech Jaruzelski","Jozef Pilsudski", "Władysław Sikorski", 2],
    ["Rzeka kojarzona z Wielkopolską?","Odra","Wisła", "Warta", 2],
    ["Kiedy jest Wigilia?","6 stycznia","31 grudnia", "24 grudnia", 3],
    ["Stolica Małopolski?","Lublin","Warszawa", "Krakow", 3],
    ["Poeta, XVI wiek, wprowadził język polski do poezji?","Adam Bernard Mickiewicz","Franciszka Arnsztajnowa", "Mikolaj Rej", 3],
    ["W której częsci Polski znajdują sie Góry?","poludnie","centralna", "polnoc", 1],
    ["W jakim miescie była podpisana pierwsza unia między Wielkim Księstwem Litewskim a Królestwem Polskim?","Krewno","Warszawa", "Wilno", 1],
    ["Najwyższe góry w Polsce?","Tatry","Rysy", "Tarnica", 1],
    ["Byl wybrany na prezydenta w terminie 2010 - 2015 roku w Polsce?","Bronislaw Komorowski","Aleksander Kwaśniewski", "Lech Wałęsa", 1],
    ["Koszyczek z jedzeniem, który święcimy w kościele to:","Święconka","Wędzonka", "Plecionka", 1],
    ["Jak nazywają się jajka, które święcimy na Wielkanoc?","Malowanki","Pisanki", "Kolorowanki", 2],
    ["Na wielkanocnym stole postawimy:","Zupę grzybową, karpia","Ser, mleko", "Jajka, babkę", 3],
    ["Śmigus Dyngus inaczej nazywa się","Lana niedziela","Lany poniedziałek ", "Lany wtorek", 2],
    ["Dzień, w którym idziemy do kościoła z palemką to:","Niedziela palmowa","Sobota palmowa", "Wtorek palmowy", 1],
    ["Czym katolicy oblewają się w lany poniedziałek?","Piwem","Mlekiem", "Wodą", 3],
    ["W czasie śniadania wielkanocnego dzielimy się","Jajkiem","Opłatkiem", "Uśmiechem", 1],
    ["Jemy pączki w","Niedzielę palmową","Środę popielcową", "Tłusty czwartek", 3],
    ["Jak nazywa się wieczór przed Bożym Narodzeniem","Kolacja","Wigilia", "Wieczerza", 2],
    ["Czym dzielimy się podczas Wigilii?","Chlebem","Opłatkiem", "Jajkiem", 2],
    ["Kiedy ubieramy choinkę?","24 grudnia","25 grudnia", "30 grudnia", 1],
    ["Jak nazywają się piosenki, które śpiewamy podczas Wigilii?","Gawędy","Góralskie", "Kolędy", 3],
    ["2 maja w Polsce obchodzi się","Dzień Konstytucji","Dzień Polaków za granicą", "Dzień pracy", 2],
    ["Czyj pomnik stoi na Runku Głównym w Krakowie?","Adama Mickiewicza","Fryderyka Chopina","Mikołaja Kopernika", 1],
    ["Jakie duże miasta leżą nad Bałtykiem?","Katowice, Szczecin, Poznań","Kraków, Gdańsk, Warszawa","Gdańsk, Gdynia, Szczecin", 3],
    ["Kim była żona Popiela? ","Włoską","Polką","Niemką", 3],
    ["Jake ważne wydarzenie miało miejsce w roku 1000","Zjazd w Gnieźnie","Chrzest Polski","Koronacja Bolesława Chrobrego", 1],
    ["Kiedy obchodzi się Sylwester?","31 grudnia","14 lutego","6 stycznia", 1],
    ["Kiedy obchodzi się Dzień Matki?","23 czerwca","26 maja","8 marca", 2],
    ["Kiedy obchodzi się Dzień Trzech Króli?","2 maja","6 grudnia","6 stycznia", 3],
    ["Kiedy obchodzi się Dzień Wniebowzięcia Najświętszej Marii Panny?","15 sierpnia","1 sierpnia","11 listopada", 1],
    ["Jak się nazywa czwartek 9-go tygodniu po Wielkanocy?","Tłusty","Boże Ciało","Zielone Świątki", 2],
    ["Z jakim świętem wiąże się C+M+B?","Boże Narodzenie","Wielkanoc","Święto Trzech Króli", 3],
    ["Kiedy obchodzimy Dzień Polonii?","1 maja","2 maja","3 maja", 2],
    ["Kiedy obchodzimy Andrzejki?","24 listopada","26 grudnia","29 listopada", 3],
    ["Co oznacza napis C+M+B?","Christus Mansionem Benedicat","imiona trzech mędrców","Chrystus, Maria, Bóg", 1],
    ["Ile potraw gotujemy na Wigilię?","6","7","12", 3],
    ["Jak się nazywa dzień, kiedy chłopaki obliwą wodą pięknych kobiet?","Katarzynki","Lany poniedziałek","Mikołajki", 2],
    ["Z jakim świętem wiąże się Rezurekcja?","Wielkanoc","Boże Narodzenie","Dzień Wszystkich Świętych", 1],
    ["Jaka tradycja idzie po pierwszej spowiedzi?","Święcenie jajek","Pierwsza komunia święta","Bierzmowanie", 2],
    ["Jakie święto symbolizuje baranek?","Boże Narodzenie","Sylwester","Wielkanoc", 3],
    ["Pieczone mięsa, biała kiełbasa, żurek, baby, mazurki, serniki to tradycyjne dania:","Wielkanocne","Noworoczne","Wigilijne", 1],
    ["Jakie zwierzę jest symbolem Puszczy Białowieskiej?","Orzeł","Żubr","Niedźwiedź", 2],
    ["W jakiej rzece mieszkała Syrenka?","Warta","Bug","Wisła", 3],
    ["W Mińsku jest pomnik","Adama Mickiewicza","Lecha Wałęsy","Mikołaja Kopernika", 1],
    ["W 1795 nastąpił III razbiór Polski. Na ile lat Polska zniknęła z mapy świata?","132","123","118", 2],
    ["Jak nazywa się obecnie najlepszy polski piłkarz?","Adam Małysz","Robert Kubica","Robert Lewandowski", 3],
    ["W jakim województwie leży Warszawa?","W mazowieckim","W warszawskim","W wielkopolskim", 1],
    ["Napisał epopeję narodową Pan Tadeusz","Władysław Reymont","Henryk Sienkiewicz","Adam Mickiewicz", 3],
    ["Jak nazywa się najwyższe pasmo górskie Karpat?","Tatry","Rysy","Bieszczady", 1],
    ["Jaka dynastia panowała po dynastii Piastów?","Dynastia Wazów","Dynastia Andegawenów","Dynastia Jagiellonów", 2],
    ["Co zaszyl w skórę barana Suba?","Igly","Mięso","Siarę i smolę", 3],
    ["Ile dni trwało Powstanie Warszawskie w 1944 roku?","63 dni","23 dni","96 dni", 1],
    ["Jak nazywało się polskie wojsko powstałe we Włoszech podczas zaborów?","Armia Polska","Legiony Polskie","Wojsko Polskie", 2],
    ["Jakie miasto było pierwszą stolicą Polski","Kraków","Poznań","Gniezno", 3],
    ["Jak nazywa się czas po Karnawale","Wielki Post","Adwent","Zaduszki", 1],
    ["Ludność Polski składa?","Około 40 mln ludzi","Około 38 mln ludzi","Około 32 mln ludzi", 2],
    ["W jakim paśmie górskim leżą Rysy?","W Sudetach","W Mazurach","W Tatrach", 3],
    ["Co łączy Romana Połańskiego, Andrzeja Wajdę i Krzysztofa Kieślowskiego?","Są reżyserami filmowymi","Są pisarzami","Są poetami", 1],
    ["Kto został Naczelnikiem Państwa po odzyskaniu niepodliegłości w 1918 roku?","Gabriel Narutowicz","Józef Piłsudski","Władysław Sikorski", 2],
    ["Jak przebiega zachodnia granica Polski","Wzdłuż rzek: Odry i Wisly","Wzdłuż rzek: Odry i Warty","Wzdłuż rzek: Odry i Nysy Łużyckiej", 3],
    ["Kto jest obecnym premierem Polski?","Mateusz Morawiecki","Andrzej Duda","Beata Szydło", 1],
    ["Czyj pomnik stoi na rynku Głownym w Krakowie?","Mikołaja Kopernika","Adama Mickiewicza","Frederyka Chopina", 2],
    ["Klasztor na Jasnej Górze znajduje się w:","Warszawie","Krakowie","Częstochowie", 3],
    ["Dlia którego miasta Daniel zrobił rzeźbę Lwów","Gdańsk","Poznań","Kraków", 1],
    ["Gdzie koronowano Bolesława Chrobrego na króla Polski?","W Gdańsku","W Gnieźnie","W Krakowie", 2],
    ["Toruń to miasto, w którym mieszkal:","Adam Mickiewicz","Józef Piłsudski","Mikołaj Kopernik", 3],
    ["Jak nazywa się najwybitniejszy współczesny polski kompozytor?","Krzysztof Penderecki","Karol Szymanowski","Stanisław Moniuszko", 1],
    ["Gdzie powstały Legiony Polskie","W Polsce","We Włoszech","We Francji", 2],
    ["Co to jest Rezurekcja?","Śniadanie wielkanocne","Śniadanie wigilijne","Msza odprawiana w Wielką Sobotę w nocy o północy", 3],
    ["Kto panował w Krakowie, gdy pojawił się smok?","Król Skuba","Król Krak","Karol Józef Wojtyła", 2],
    ["Którego dnia obchodzi się w Polsce Dzień Flagi","1 maja","2 maja","3 maja", 2],
    ["Czy Józef Piłsudski był premierem Polski","tak - dwa razy","nie","tak - jeden raz", 1],
    ["Jak nazywa się pierwsza dynastia królów Polski?","Dynastia Wazów","Dynastia Jagiellonów","Dynastia Piastów", 3],
    ["Kto był przewodniczącym związku zawodowego Solidarność?","Lech Wałęsa","Lech Kaczyński","Andrzej Duda", 1],
    ["Jakie mejsce jest \"zimową stolicą Polski\" i gdzie ono znajduje?","Sudety. Znajduje się niedaleko od granicy z Czechami","Tatry. Znajduje się niedaleko od granicy z Czechami","Zakopane. Znajduje się niedaleko od Krakowa", 3],
    ["Za jaką powieść Władysław Rejmont otrzymał Nagrodę Nobla?","Chłopi","Quo Vadis","Ziemia Obiecana", 1],
    ["Najwyższy szczyt w Polsce to","śnieżka","Tatry","Rysy", 3],
    ["Gdzie w Polsce leży pustynia","Niedaleko Warszawy","Nidaleko Białegostoku","Na pograniczu wyżyny śląskiej i olkuskiej", 3],
    ["Flaga Polski jest podzielona na dwa równe poziome pasy. Jakich kolorów są te pasy?","Czerwony na górze, biały na dole","Biały na górze, czerwony na dole","Nebeski na gorze, bialły na dole", 2],
    ["Przywódca powstania narodowego z 1794 roku - o kim mowa","Tadeusz Kościuszko","Józef Piłsudski","Krzysztof Penderecki", 1],
    ["Kto był 11 listopada 1918 naczelnym wodzem Armii Polskiej?","Lech Wałęsa","Władysław Sikorski","Józef Piłsudski", 3],
    ["W kogo zamieniła się Złota Kaczka?","W starą kobietę","W królewnę","W ptaka", 2],
    ["Jak nazywał się Jan Paweł II zanim został papieżem?","Stanisław Dziwisz","Karol Wojtyłła","Kazimierz Nycz", 2],
    ["Gdzie w Warszawie znajduje się pomnik Fryderyka Chopina?","W Wilanowie","Na Starym Mieście ","W Łazienkach", 3],
    ["W którym roku zmarł Jan Paweł II?","2005","2008","2010", 1],
    ["Kto z niżej wymienionych otrzymał Pokojową Nagrodę Nobla?","Lech Kaczyński","Lech Wałęsa","Wojciech Jaruzelski", 2],
    ["Twórca polskiej opery to:","Krzysztof Penderecki","Stanisław Moniuszko","Karol Szymanowski", 2],
    ["Kto namalował obraz \„Bitwa pod Grunwaldem\”?","Jan Matejko","Stanisław Wyspiański","Jacek Malczewski", 1],
    ["O kim w przenośni mówimy, że wstrzymał Słońce, ruszył Ziemię?","Maria Skłodowska-Curie","Henryk Arctowski","Mikołaj Kopernik", 3],
    ["Polski naukowiec, Henryk Arctowski, brał udział w wyprawie:","do Australii","do Afryki","do Antarktyki", 3],
    ["Jak nazywał się Naczelny Wódz Polskich Sił Zbrojnych i premier Rządu na Uchodźstwie podczas II wojny światowe, który ginął w katastrofie lotniczej na Gibraltarze?","Władysław Anders","Władysław Sikorski","Karol Świerczewski ", 2],
    ["Twórca i dowódca Polskich Sił Zbrojnych w ZSRR, powstałej z ochotników uratowanych z więzień i łagrów.","Władysław Anders","Władysław Sikorski","Karol Świerczewski", 1],
    ["Uważany jest za jednego z najwybitniejszych twórców renesansu w Europie i poetę, który najbardziej przyczynił się do rozwoju polskiego języka literackiego.","Mikołaj Rej","Mikołaj Kopernik","Jan Kochanowski ", 3],
    ["Gdzie urodził się Fryderyk Chopin?","W Warszawie","W Żelazowej Woli","W Krakowie", 2],
    ["W którym roku powstało Księstwo Warszawskie?","1807","1827","1817", 1],
    ["W którym roku Zakon Krzyżacki został sprowadzony do Polski?","1315","1226","966", 2],
    ["Pod jakimi zaborami znajdowała się Polska?","Ruskimi, Austriackimi, Czeskimi","Ruskimi, Pruskimi, Tureckimi","Ruskimi, Austriackimi, Pruskimi", 3],
    ["Kim był Roman Dmowski?","Sławny, polski polityk","Sławny, polski artysta","Sławny, polski sportowiec", 1],
    ["Jakie znaczenie miała Bitwa Warszawska \"Cud nad Wisłą\"?","Powstrzymanie Hitlera przed dalszą ekspansją","Powstrzymanie inwazji Bolszewizmu na Europę","Wyzwolenie się od okupacji Austrii", 2],
    ["W jakim wieku Polska przeżywała swój \"Złoty wiek\"?","XV","XVII","XVI", 3],
    ["Jak nazywał się drugi król Polski?","Mieszko II Lambert","Władysław I Herman","Bolesław I Chrobry ", 1],
    ["W którym roku powstał \"Mazurek Dąbrowskiego\"?","1927","1797","1863", 2],
    ["W którym kraju znajduje się Góra Kościuszki?","Szwajcaria","USA","Australia", 3],
    ["Podaj nazwisko ministra zbrojeń III rzeszy który panował w latach 1942-1945","Albert Speer","Heinrich Himmler","Joseph Goebbels", 1],
    ["Władysław Warneńczyk zmarł w czasie bitwy na Warną. Miał wtedy:","18 lat","20 lat","29 lat", 2],
    ["Powstanie Warszawskie miało miejsce w roku:","1863","1939","1944", 3],
    ["Konstytucję 3 Maja wprowadzono w…","1791","1795","1927", 1],
    ["W którym roku złożony został hołd pruski?","1525","1533","1535", 1],
    ["W którym roku Konrad Mazowiecki sprowadził do Polski Krzyżaków?","966","1262","1236", 2],
    ["Największe jezioro w Polsce","Jeziorak","Wigry","Śniardwy", 3],
    ["Jak miała na imię syrena z legendy o Warszawie?","Sawa","Basia","Warsa", 1],
    ["Reżyserem filmu \"Ogniem i mieczem\" jest","Andrzej Wajda","Roman Polański","Jerzy Hoffman", 3],
    ["Rodzeństwo to","Mama i ojciec","Bracia i siostry ","Mama, ojciec, bracia, siostry, żona", 2],
    ["Kto z kompozytorów polskich uczył się i mieszkał w Mińsku?","Fryderyk Chopin","Stanisław Moniuszko","Jan Kaczmarek", 2],
    ["Władysław Reymont dostał nagrodę Nobla w dziedzinie","Chemii","Fizyki","Literatury", 3],
    ["Czesław Miłosz to","Poeta","Pisarz","Kompozytor", 1],
    ["Co zapisał w swoim testamencie Bolesław Krzywousty?","Jedność Polski","Podzielił Polskę pomiędzy Rosję, Austrię i Litwę","Podzielił Polskę pomiędzy swoich synów ", 3],
    ["Gdzie i jak zginął Święty Wojciech?","Odcięto mu głowę na Litwie","Został zabity kamieniami na terenie Rusi","Został uderzony toporem lub włócznią w serce na terenie pogańskich Prusów", 3],
    ["Podaj dokładną datę urodzin i śmierci Jana Pawła II","18 maja 1920, 2 kwietnia 2005","18 lipca 1919, 2 maja 2006","8 maja 1921, 2 kwietnia 2007", 1],
    ["Kto był królem Polski w 1791 r.","Jan III Sobieski","Kazimierz Wielki","Stanisław August Poniatowski", 3],
    // ["","","","", ],
    // ["","","","", ],
    // ["","","","", ],
    // ["","","","", ],
];